os:
- osx

language: go

go:
- 1.11.5

addons:
  apt:
    packages:
    - libsecret-1-dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update -q && sudo apt-get install pkg-config -y;
  fi

script:
- GO111MODULE=on GOFLAGS=-mod=vendor go test -v ./...
- GO111MODULE=on GOFLAGS=-mod=vendor go build -v

after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export FILE_TO_UPLOAD=mobingi-${TRAVIS_TAG}-darwin-amd64.tar.gz;
  else
    export FILE_TO_UPLOAD=mobingi-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-amd64.tar.gz;
  fi
- tar cvzf ${FILE_TO_UPLOAD} mobingi
- ls -laF

deploy:
  provider: releases
  api_key:
    secure: bYpTt3c999V+ZPsxh4ymXwiHzgzDnhHZgsxBXKOMS/m34EgrVvJOPs2mOTEtQCYUzjRQagPCymO/CI4nFK0x1a3Hg6tezb6sQnL9sTvkfhnstMDiX+CX+IHzQFUtRMC5gNNn/46TwfVX18PwAgjbUrNWUvk+bC+vOhHZsu8qi+AChvd7cbIriv8mS3K6Z1o6fI8e9+A0FJvX5WADeZ+YFZYs4KizmOZlu4x8kj9kkWNN6/rYX1ifszSOH+1QG03oSlBemCBYeDH6FaYuN/I5PAXqlibcmIF5hWD78vLh4DqQ/rrGlWF1EhM7u3OMAvNFj0pe5Cbia3vf195yGIPJsX74tF1UdyewIfBW8FX7fI4xnL6sNild1CNCSXlFXuIUoqmii70j1zDwDnLfq5RJ5+D9+JgexFMsUk5TfSJ0BOGofaKeuTSti83XvOmpa3Jz2MrRrfR12nj4RL4ilkrBYykR1nqf+uaHg6cDVSzDyBBCzz6bPgqpjGs/2rLiKKP5siMSnt9+CO+FnSG47SZ0joEkt0F1bdJgPTkuglnaW/OO82QpsEtZpp8oMAX/0Leos4QXHJSMHBKJMdWGfTdq1t/XLt+XWhc06cRGXwabmgt+w8ANeDzwZJVdjQIYxhBseeezC3b1CO6tOSzbqCrECvmgzPH8a6z3QqV1TeeRMZU=
  file: '${FILE_TO_UPLOAD}'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  slack:
    secure: C8FVdl0GIucS3dRXbe3p4/ujfDeA0ubk572EFo47VfU1tBdaDi9C8ouqvapaknRHwDtvbOtdiR9HylNp/C5veFou4osmoRIprET9hf5XsJd/0vlu8JdxJzuRnRfE6I3uhdb2vNjHxWHQhx7MK5LPEfIjMDXOfZkT5idrWPl3OKMHFDBX5KMBvIj0zYsRhVnphwNxJOJLJtJk2VGMWasqcs8kGcOSPrtivBS6PKyJSTQEVQ3lngUrnJx2ly7MTXvYJfGA+xMNfZY85aDF/PqQ7VcjwkE+TgKX3wVJBkI4Iu1anGAGFD7rEYmnINJLKQntPmr0QBKOXOS/Fdm9i0CnHMwYrDLYKIokRlRc6zZNTXmEsBPZVyOakUSUTk/E5qFhIafYQYIxOgyz0r2n3OqlkPJ352ZLbopWTilJsn80Tsmh0pCncvqway+Cn2DYHnPuI4C+ncFOjiOmP9I2YQkAYo31+yutPqKArjUBHx4oqaV0kExhwpliV1vVezkddgmtomFrgP9EjqQDaiuvPnnTnxvIhhXKSRBJP9QrnqvQ1KVpxrqfJ9EDGlckCRy5/w57KA7YxdE3GGhl/hw/OBGcb5SDmrMjSTbmvGcdfW4nRaF9bL5uroZ2gHAN/zX6ae++27qqoJPMBOVpfI4kktGmvU2WhdQcvVGD1IeTargHWg4=
