version: "{build}"

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\mobingi\mobingi

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11.5

install:  
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set GOFLAGS=-mod=vendor
  - go version
  - go env

build_script:
  - go build -v

after_build:
  - 7z a mobingi-%APPVEYOR_REPO_TAG_NAME%-windows-amd64.zip %APPVEYOR_BUILD_FOLDER%\mobingi.exe
  - dir /w
  
artifacts:
  - path: mobingi-$(appveyor_repo_tag_name)-windows-amd64.zip
    name: mobingi

deploy:
  provider: GitHub
  auth_token:
    secure: kBFWX6rgl9iy7aw+3psKgFDM+ougnfSsSmFxgQILcML015b2u6W5jzIXHmIKIq+L
  artifact: mobingi
  # draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    incoming_webhook:
      secure: JrW1YiaNWR8kRkpmFriLtdpVPuYsQCI9Moadv4158OwIERSuWfHs1CHREUPpZ9l6K43yEEZdOptPxpHCRLfjqr1CByqMxHx/zdWcUCHM3Ag=
