version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.11.5
      
    working_directory: /go/src/github.com/mobingi/mobingi
    steps:
    - checkout

    - run:
        name: build
        shell: /bin/bash
        command: |
          GO111MODULE=on GOFLAGS=-mod=vendor go test -v ./...
          GO111MODULE=on GOFLAGS=-mod=vendor go build -v
          ls -laF

